#!/bin/bash -ux

# OpenStack
for CHANNEL in {train,ussuri,victoria,wallaby,xena,yoga,zed,latest}/{edge,beta,candidate,stable}; do
    charmhub-lp-tool --config-dir ./release-tools/lp-builder-config/ \
        --log DEBUG \
        -p openstack \
        -f html \
        check-builds \
        --channel $CHANNEL \
        --output ./report/$(echo $CHANNEL  | tr / -).html
done
# Ceph
for CHANNEL in {luminous,mimic,nautilus,octopus,pacific,quincy,latest}/{edge,beta,candidate,stable}; do
    charmhub-lp-tool --config-dir ./release-tools/lp-builder-config/ \
        --log DEBUG \
        -p ceph \
        -f html \
        check-builds \
        --channel $CHANNEL \
        --output ./report/$(echo $CHANNEL  | tr / -).html
done
# OVN
for CHANNEL in {20.03,20.12,21.09,22.03,22.09,latest}/{edge,beta,candidate,stable}; do
    charmhub-lp-tool --config-dir ./release-tools/lp-builder-config/ \
        --log DEBUG \
        -p openstack \
        -f html \
        check-builds \
        --channel $CHANNEL \
        --output ./report/$(echo $CHANNEL  | tr / -).html
done

LIST_OF_LINKS=""
pushd report
for REPORT in $(ls *.html); do
  if [ "$REPORT" != "index.html" ]; then
    LIST_OF_LINKS=$(echo "$LIST_OF_LINKS <li class='p-list__item'><a href='./${REPORT}'>${REPORT}</a></li>")
  fi
done
popd

cat << EOF > report/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Charms</title>
  <link rel="stylesheet" href="https://assets.ubuntu.com/v1/vanilla-framework-version-3.8.1.min.css" />
</head>
<body>
  <div class="l-site">
    <div class="u-fixed-width">
      <ul class="p-list">
        ${LIST_OF_LINKS}
      </ul>
    </div>
    <footer class="l-footer--sticky p-strip--light">
      <nav class="row" aria-label="Footer">
        <div class="has-cookie">
          <p>Report generated by <a href="https://github.com/openstack-charmers/charmhub-lp-tools/">charmhub-lp-tools</a> (<i>$(date)</i>)</p>
        </div>
      </nav>
    </footer>
  </div>
</body>
</html>
EOF
